all: 4 5 6 7 8 9 10 11 12 13 14 15

4: 
	$(MAKE) -C project4 
5: 
	$(MAKE) -C project5 
6: 
	$(MAKE) -C project6 
7: 
	$(MAKE) -C project7 
8: 
	$(MAKE) -C project8 
9: 
	$(MAKE) -C project9 
10: 
	$(MAKE) -C project10 
11: 
	$(MAKE) -C project11 
12: 
	$(MAKE) -C project12 
13: 
	$(MAKE) -C project13 
14: 
	$(MAKE) -C project14 
15:
	$(MAKE) -C project15

test: 4t 5t 6t 7t 8t 9t 10t 11t 12t 13t 14t 15t

4t: 
	$(MAKE) -C project4 test
5t: 
	$(MAKE) -C project5 test
6t: 
	$(MAKE) -C project6 test
7t: 
	$(MAKE) -C project7 test
8t: 
	$(MAKE) -C project8 test
9t: 
	$(MAKE) -C project9 test
10t: 
	$(MAKE) -C project10 test
11t: 
	$(MAKE) -C project11 test
12t: 
	$(MAKE) -C project12 test
13t: 
	$(MAKE) -C project13 test
14t: 
	$(MAKE) -C project14 test
15t:
	$(MAKE) -C project15 test

clean: 4c 5c 6c 7c 8c 9c 10c 11c 12c 13c 14c 15c

4c: 
	$(MAKE) -C project4 clean
5c: 
	$(MAKE) -C project5 clean
6c: 
	$(MAKE) -C project6 clean
7c: 
	$(MAKE) -C project7 clean
8c: 
	$(MAKE) -C project8 clean
9c: 
	$(MAKE) -C project9 clean
10c: 
	$(MAKE) -C project10 clean
11c: 
	$(MAKE) -C project11 clean
12c: 
	$(MAKE) -C project12 clean
13c: 
	$(MAKE) -C project13 clean
14c: 
	$(MAKE) -C project14 clean
15c:
	$(MAKE) -C project15 clean